apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: skaffold-fastapi
build:
  artifacts:
    - image: fastapi
      context: fastapi
  local:
    push: false
manifests:
  # rawYaml:
  #   - ./k8-yaml-files/namespace.yaml
  #   - ./k8-yaml-files/dockerconfigjson.yaml
  #   - ./k8-yaml-files/ingress-nginx.yaml
  helm:
    releases:
      - name: fastapi
        skipTests: true	# Because kind clusters is not okayish with tests
        chartPath: ./fastapi/helm-chart
        valuesFiles:
          - ./fastapi/dev.env.yaml
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO_fastapi }}"
          image.tag: "{{ .IMAGE_TAG_fastapi }}"
          # Used skaffold-generated image repo and tag for our deployment. For more https://skaffold.dev/docs/deployers/helm/
portForward:
  - resourceType: deployment
    resourceName: fastapi # Find the exact resource name using this command `kubectl get deployments`
    port: 8080
    address: 0.0.0.0
    localPort: 8080
