apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi.fullname" . }}-secrets
type: Opaque
data:
{{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}