# Pass all secret values here.
secrets:
  ENVVARIABLE1: "envvalue1"
  ENVVARIABLE2: "envvalue2"

imagePullSecrets: [] # For Example: [{ name: dockerconfigjson-github-com }]

resources:
  limits:
    cpu: 250m # 25% of 1 CPU core
    memory: 256Mi
  requests:
    cpu: 250m # 25% of 1 CPU core
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10 # Edit the max replica you want
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80